/*******************************************************************************
*
* Program: Generate A Random Boolean
* 
* Description: Example of generating a random boolean true/false value using C.
*
* YouTube Lesson: https://www.youtube.com/watch?v=29U5PZfniYs 
*
* Author: Kevin Browne @ https://portfoliocourses.com
*
*******************************************************************************/

#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <time.h>

bool random_bool();

int main(void)
{
  // Seed the random number generator with the current time to help ensure the 
  // sequence of random numbers generated by rand() will be different each time
  // the program runs.
  srand(time(NULL));

  // In C the value 0 is considered 'false' and 1 (or any non-zero integer) is 
  // considered 'true'.  Starting in the C23 standard of the language there is 
  // a bool type with true (1) and false (0) values.  In C99 onwards we can 
  // include stdbool.h to ensure we have the bool type and values true/false 
  // (which again are really just 1 and 0 respectively).
  //
  // So if we can generate a random integer that is either 0 or 1 we can 
  // essentially generate a random 'boolean' that is either false or true.

  // Declare a bool variable to store the random bool
  bool bool_value;

  // Store the random bool returned by random_bool() into bool_value
  bool_value = random_bool(); 

  // Output whether the random bool is true or false
  if (bool_value) printf("bool_value is true\n");
  else printf("bool_value is false\n");
  
  return 0;
}

// Returns either true (1) or false (0) randomly
bool random_bool()
{
  // The rand() function returns a random integer in the range of 0...RAND_MAX
  // where RAND_MAX is a large positive integer.  If we take this integer and
  // divide it by 2 the only possible remainders are 0 (false) and 1 (true).
  // So we use the modulus operator % which returns the remainder of a division
  // operation to divide the number returned by rand() by 2 and we return 
  // the result!
  //
  return rand() % 2;
}